name: Automatically Build image on tag
env:
        DOCKER_CLI_EXPERIMENTAL: enabled
        TAG_FMT: '^refs/tags/(((.?[0-9]+){3,4}))$'

on:
        push:
                tags: [ '*' ]

jobs:
        build:
                runs-on: ubuntu-18.04
                name: Build / Push Umbrel Dashboard on version tag
                steps:
                        - name: Setup Environment
                          run: |
                                  if ! echo "$GITHUB_REF" | grep -qE "$TAG_FMT"; then
                                        echo "ERR: TAG must be in format: vX.Y.Z or X.Y.Z or vW.X.Y.Z or W.X.Y.Z"
                                        exit 1
                                  fi
                                  VERSION="$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\2|")"
                                  
                                  TAG="$(echo "$GITHUB_REF" | sed -E "s|$TAG_FMT|\1|")"
                                  echo ::set-env name=TAG::"$TAG"
                                  
                        - name: Show set environment variables
                          run: |
                                  printf "    TAG: %s\n"  "$TAG"                                  
                        - name: Login to Docker for building
                          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                        - name: Checkout project
                          uses: actions/checkout@v2
                        - name: Setup Docker buildx Action
                          uses: crazy-max/ghaction-docker-buildx@v1
                          id: buildx
                          with:
                                  buildx-version: latest
                                  qemu-version: latest
                        - name: Available platforms
                          run: echo ${{ steps.buildx.outputs.platforms }}
                        - name: Run Docker build X (against tag)
                          run: |
                                  docker buildx build \
                                  --platform linux/amd64,linux/386,linux/arm/v7,linux/arm64 \
                                  -t getumbrel/manager:$TAG \
                                  --output "type=registry" \
                                  .
                        - name: Run Docker build X (against latest)
                          run: |
                                  docker buildx build \
                                  --platform linux/amd64,linux/386,linux/arm/v7,linux/arm64 \
                                  -t getumbrel/manager:latest \
                                  --output "type=registry" \
                                  .
                        - name: Run Docker buildx (against stage)
                          run: |
                                docker buildx build \
                                --platform linux/amd64 \
                                -f ./Dockerfile.stage \
                                -t getumbrel/manager:stage \
                                --output "type=registry" \
                                .